# tif-handling.py
# Functions to handle tif files generated by cellpose

import numpy as np
from PIL import Image

def read_multiframe_tiff(filename):
    img = Image.open(filename)
    frames = []

    for i in range(img.n_frames):
        img.seek(i)
        frames.append(np.array(img))

    return np.array(frames)